const carouselAPI = () => ([
    {
        id: 1,
        title: "Uncharted",
        image: 'https://asset.kompas.com/crops/N2W-VbMNsgCKljC3c_AVWyIM24M=/0x147:1080x867/750x500/data/photo/2022/02/16/620ca3d92d136.jpg',
        genre: "Action, Adventure",
        overview: "Street-smart Nathan Drake (Tom Holland) is recruited by seasoned treasure hunter Victor 'Sully' Sullivan (Mark Wahlberg) to recover a fortune amassed by Ferdinand Magellan and lost 500 years ago by the House of Moncada. What starts as a heist job for the duo becomes a globe-trotting, white-knuckle race to reach the prize before the ruthless Santiago Moncada (Antonio Banderas), who believes he and his family are the rightful heirs. If Nate and Sully can decipher the clues and solve one of the world's oldest mysteries, they stand to find $5 billion in treasure and perhaps even Nate's long-lost brother...but only if they can learn to work together",
        next: "#2",
        prev: "#7",
    },
    {
        id: 2,
        title: "Top Gun - Maverick",
        image: 'https://cdn-asset.jawapos.com/wp-content/uploads/2022/08/20220829_081414.jpg',
        genre: "Action, Drama",
        overview: "Set 30 years after its predecessor, it follows Maverick's return to the United States Navy Strike Fighter Tactics Instructor program (also known as U.S. Navy-Fighter Weapons School - TOPGUN), where he must confront his past as he trains a group of younger pilots, among them the son of Maverick's deceased best friend Lieutenant Nick 'Goose' Bradshaw, USN",
        next: "#3",
        prev: "#1",
    },
    {
        id: 3,
        title: "Black Adam",
        image: 'https://djavatoday.com/wp-content/uploads/2022/10/IMG-20221014-WA0085.jpg',
        genre: "Action, Adventure, Fantasy",
        overview: "Reawakening after 5000 years, Black Adam becomes the world's ruthless protector: an anti-villain to take on the likes of Superman and Wonder Woman. Now in the 21st-Century, Black Adam must face off against the Justice Society of America and it's heroes: Doctor Fate, Hawkman, Atom Smasher and Cyclone. The fate of the world hangs in the balance.",
        next: "#4",
        prev: "#2",
    },
    {
        id: 4,
        title: "Black Panther - Wakanda Forever",
        image: 'https://www.ruparupa.com/blog/wp-content/uploads/2022/10/fakta-menarik-black-panther-2.jpg',
        genre: "Action, Adventure, Sci-Fi",
        overview: "After the events of Captain America: Civil War, Prince T'Challa returns home to the reclusive, technologically advanced African nation of Wakanda to serve as his country's new king. However, T'Challa soon finds that he is challenged for the throne from factions within his own country. When two foes conspire to destroy Wakanda, the hero known as Black Panther must team up with C.I.A. agent Everett K. Ross and members of the Dora Milaje, Wakandan special forces, to prevent Wakanda from being dragged into a world war",
        next: "#5",
        prev: "#3",
    },
    {
        id: 5,
        title: "Morbius",
        image: 'https://www.tipspintar.com/wp-content/uploads/2022/03/Fin-Banner-Morbius.jpg',
        genre: "Action, Adventure, Horror",
        overview: "Dangerously ill with a rare blood disorder, and determined to save others suffering his same fate, Dr. Morbius attempts a desperate gamble. What at first appears to be a radical success soon reveals itself to be a remedy potentially worse than the disease.",
        next: "#6",
        prev: "#4",
    },
    {
        id: 6,
        title: "Minions - The Rise of Gru",
        image: 'https://images.soco.id/68-Review-Minions-The-Rise-of-Gru-1.jpg.jpg',
        genre: "Animation, Adventure, Comedy",
        overview: "In the heart of the 1970s, amidst a flurry of feathered hair and flared jeans, Gru (Steve Carell) is growing up in the suburbs. A fanboy of a supervillain supergroup known as the Vicious 6, Gru hatches a plan to become evil enough to join them. Luckily, he gets some mayhem-making back-up from his loyal followers, the Minions. Together, Kevin, Stuart, Bob, and Otto - a new Minion sporting braces and a desperate need to please - deploy their skills as they and Gru build their first lair, experiment with their first weapons, and pull off their first missions. When the Vicious 6 oust their leader, legendary fighter Wild Knuckles (Alan Arkin), Gru interviews to become their newest member. It doesn't go well (to say the least), and only gets worse after Gru outsmarts them and suddenly finds himself the mortal enemy of the apex of evil",
        next: "#7",
        prev: "#5",
    },
    {
        id: 7,
        title: "Sea Beast",
        image: 'https://porosmedia.com/wp-content/uploads/2022/07/Sinopsis-The-Sea-Beast-Film-Animasi-Petualang-Gadis-Cilik-Memburu-Monster-Laut.jpg',
        genre: "Animation, Adventure, Comedy",
        overview: "In an era when terrifying beasts roamed the seas, monster hunters were celebrated heroes and none were more beloved than the great Jacob Holland. But when young Maisie Brumble stows away on his fabled ship, he's saddled with an unexpected ally. Together they embark on an epic journey into uncharted waters and make history.",
        next: "#1",
        prev: "#6",
    },
]);

export {carouselAPI};