const getMoviesData = () => ([
    {
        id: 1,
        href:"slide1",
        prev:"#slide8",
        next:"#slide2",
        title: "Black Panther: Wakanda Forever",
        overview: "Lorem Ipsum is simply dummy text...",
        genre: "Action, Adventure, Drama",
        desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
        image: "https://m.media-amazon.com/images/M/MV5BNTM4NjIxNmEtYWE5NS00NDczLTkyNWQtYThhNmQyZGQzMjM0XkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_FMjpg_UX1000_.jpg",
    },
    {
        id: 2,
        href:"slide2",
        prev:"#slide1",
        next:"#slide3",
        title: "Black Adam",
        overview: "Lorem Ipsum is simply dummy text...",
        genre: "Action, Adventure, Fantasy",
        desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
        image: "https://m.media-amazon.com/images/M/MV5BYzZkOGUwMzMtMTgyNS00YjFlLTg5NzYtZTE3Y2E5YTA5NWIyXkEyXkFqcGdeQXVyMjkwOTAyMDU@._V1_.jpg",
    },
    {
        id: 3,
        href:"slide3",
        prev:"#slide2",
        next:"#slide4",
        title: "Sri Asih",
        overview: "Lorem Ipsum is simply dummy text...",
        genre: "Action, Sci-Fi",
        desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
        image: "https://m.media-amazon.com/images/M/MV5BY2UzNDYxZjItNTE4Yy00ZTQ2LWE1NGQtYWZhMWE1NjhlYzlhXkEyXkFqcGdeQXVyNzY4NDQzNTg@._V1_FMjpg_UX1000_.jpg",
    },
    {
        id: 4,
        href:"slide4",
        prev:"#slide3",
        next:"#slide5",
        title: "Satria Dewa: Gatotkaca",
        overview: "Lorem Ipsum is simply dummy text...",
        genre: "Action, Adventure, Drama",
        desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
        image: "https://m.media-amazon.com/images/M/MV5BOWEzN2IxOTktMzBjMS00ZWU1LWI0OTgtZjViNWYxOWY1MjUxXkEyXkFqcGdeQXVyNzY4NDQzNTg@._V1_FMjpg_UX1000_.jpg",
    },
    {
        id: 5,
        href:"slide5",
        prev:"#slide4",
        next:"#slide6",
        title: "Monster Hunter",
        overview: "Lorem Ipsum is simply dummy text...",
        genre: "Action, Adventure, Fantasy",
        desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
        image: "https://m.media-amazon.com/images/M/MV5BOTMyZThmYzEtN2UzNC00YmI4LWFhZmUtZjQ4Nzc0NzhkZjhlXkEyXkFqcGdeQXVyMTA3MDk2NDg2._V1_.jpg",
    },
    {
        id: 6,
        href:"slide6",
        prev:"#slide5",
        next:"#slide7",
        title: "Minions: Rise of Gru",
        overview: "Lorem Ipsum is simply dummy text...",
        genre: "Animation, Adventure, Comedy",
        desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
        image: "https://m.media-amazon.com/images/M/MV5BZDFhZTZiYmYtZmRiNC00YzQ2LWE0MmMtYWUwMzcxN2M1MzhmXkEyXkFqcGdeQXVyMTQyMTMwOTk0._V1_.jpg",
    },
    {
        id: 7,
        href:"slide7",
        prev:"#slide6",
        next:"#slide8",
        title: "The Ice Age: Adventure of Buck Wild",
        overview: "Lorem Ipsum is simply dummy text...",
        genre: "Animation, Adventure, Comedy",
        desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
        image: "https://m.media-amazon.com/images/M/MV5BNDJmMzQyMzAtMzMxMy00NTI3LTgzOGMtZDU3Yzc4MjRjNzkwXkEyXkFqcGdeQXVyMTA1OTcyNDQ4._V1_FMjpg_UX1000_.jpg",
    },
    {
        id: 8,
        href:"slide8",
        prev:"#slide7",
        next:"#slide1",
        title: "Thor: Love and Thunder",
        overview: "Lorem Ipsum is simply dummy text...",
        genre: "Action, Adventure, Comedy",
        desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
        image: "https://m.media-amazon.com/images/M/MV5BYmMxZWRiMTgtZjM0Ny00NDQxLWIxYWQtZDdlNDNkOTEzYTdlXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_FMjpg_UX1000_.jpg",
    },
]);

export {getMoviesData};